CREATE TABLE BRN (
    BRN_ID              NUMBER(11, 0),
    EMPLOYEE_ID         NUMBER(11, 0),
    BOOKING_DATE        DATE DEFAULT SYSDATE,
    CHECK_IN_DATE       DATE DEFAULT SYSDATE,
    CHECK_OUT_DATE      DATE DEFAULT SYSDATE,
    STATUS              VARCHAR(10),
    TOTAL_COST          NUMBER(9, 2),
    PAYMENT_DETAILS_ID  NUMBER(11, 0),
CONSTRAINT BRN_PK PRIMARY KEY (BRN_ID),
CONSTRAINT EMPLOYEE_ID_FK1 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
CONSTRAINT PAYMENT_DETAILS_ID_FK2 FOREIGN KEY (PAYMENT_DETAILS_ID) REFERENCES PAYMENT_DETAILS(PAYMENT_DETAIL_ID));

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID         NUMBER(11, 0),
    FIRST_NAME          VARCHAR(30),
    MIDDLE_NAME         VARCHAR(20),
    LAST_NAME           VARCHAR(20),
    BIRTHDAY            DATE DEFAULT SYSDATE,
    ADDRESS             VARCHAR(70),
    CONTACT_NUMBER      NUMBER(11),
    EMAIL_ADDRESS       VARCHAR(40),
    AGE                 NUMBER(3, 0),
    SUPERVISOR          NUMBER(11, 0),
    EMPLOYEE_TYPE       VARCHAR(2),
CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID),
CONSTRAINT EMPLOYEE_ID_FK1 FOREIGN KEY (SUPERVISOR) REFERENCES EMPLOYEE(EMPLOYEE_ID));

CREATE TABLE GUEST (
    GUEST_ID            NUMBER(11, 0),
    FIRST_NAME          VARCHAR(30),
    MIDDLE_NAME         VARCHAR(20),
    LAST_NAME           VARCHAR(20),
    BIRTHDAY            DATE DEFAULT SYSDATE,
    ADDRESS             VARCHAR(70),
    CONTACT_NUMBER      NUMBER(11),
    EMAIL_ADDRESS       VARCHAR(40),
    AGE                 NUMBER(3, 0),
CONSTRAINT GUEST_PK PRIMARY KEY (GUEST_ID));

CREATE TABLE BRN_GUEST (
    BRN_ID          NUMBER(11, 0),
    GUEST_ID        NUMBER(11, 0),
    GUEST_TYPE      VARCHAR(1),
CONSTRAINT BRN_GUEST_PK PRIMARY KEY (BRN_ID, GUEST_ID),
CONSTRAINT BRN_ID_FK1 FOREIGN KEY (BRN_ID) REFERENCES BRN(BRN_ID),
CONSTRAINT GUEST_ID_FK2 FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID));

CREATE TABLE CHARGE (
    CHARGE_ID       NUMBER(11, 0),
    BRN_ID          NUMBER(11, 0),
    ROOM_NUMBER     NUMBER(3, 0),
    CHARGE_DATE     DATE DEFAULT SYSDATE,
    COST            NUMBER(7, 2),
CONSTRAINT CHARGE_PK PRIMARY KEY (CHARGE_ID),
CONSTRAINT BRN_ID_FK1 FOREIGN KEY (BRN_ID) REFERENCES BRN(BRN_ID),
CONSTRAINT ROOM_NUMBER_FK2 FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOM(ROOM_NUMBER));

CREATE TABLE SERVICE_LINE (
    SERVICE_LINE_ID     NUMBER(11, 0),
    SERVICE_ID          NUMBER(11, 0),
    EMPLOYEE_ID         NUMBER(11, 0),
    CHARGE_ID           NUMBER(11, 0),
    SERVICE_DATE        DATE DEFAULT SYSDATE,
CONSTRAINT SERVICE_LINE_PK PRIMARY KEY (SERVICE_LINE_ID),
CONSTRAINT SERVICE_ID_FK1 FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID),
CONSTRAINT EMPLOYEE_ID_FK2 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
CONSTRAINT CHARGE_ID_FK3 FOREIGN KEY (CHARGE_ID) REFERENCES CHARGE(CHARGE_ID));

CREATE TABLE ROOM (
    ROOM_NUMBER         NUMBER(11, 0),
    ROOM_TYPE           VARCHAR(2),
    DESCRIPTION         VARCHAR(255),
    PRICE               NUMBER(7, 2),
    MAX_GUESTS          NUMBER(2, 0),
    BEDS                NUMBER(2, 0),
    AREA                NUMBER(5, 2),
CONSTRAINT ROOM_NUMBER_PK PRIMARY KEY (ROOM_NUMBER),
CONSTRAINT ROOM_TYPE_FK1 FOREIGN KEY (ROOM_TYPE) REFERENCES ROOM_TYPE(ROOM_TYPE));

CREATE TABLE SERVICE (
    SERVICE_ID          NUMBER(11, 0),
    SERVICE_NAME        VARCHAR(30),
    EMPLOYEE_TYPE       VARCHAR(2),
CONSTRAINT SERVICE_PK PRIMARY KEY (SERVICE_ID),
CONSTRAINT EMPLOYEE_TYPE_FK1 FOREIGN KEY (EMPLOYEE_TYPE) REFERENCES EMPLOYEE(EMPLOYEE_TYPE));

CREATE TABLE SERVICE_ROOM_TYPE (
    SERVICE_ID          NUMBER(11, 0),
    ROOM_TYPE           VARCHAR(2),
    PRICE               NUMBER(7, 2),
CONSTRAINT SRT_PK PRIMARY KEY (SERVICE_ID, ROOM_TYPE),
CONSTRAINT SERVICE_ID_FK1 FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID),
CONSTRAINT ROOM_TYPE_FK2 FOREIGN KEY (ROOM_TYPE) REFERENCES ROOM_TYPE(ROOM_TYPE));

CREATE TABLE ROOM_TYPE (
    ROOM_TYPE          VARCHAR(2),
CONSTRAINT ROOM_TYPE_PK PRIMARY KEY (ROOM_TYPE));

CREATE TABLE PAYMENT_DETAILS (
    PAYMENT_DETAIL_ID       NUMBER(11, 0),
    MODE_OF_PAYMENT         VARCHAR(20),
    CARD_NUMBER             NUMBER(10, 0),
    CVV                     NUMBER(3, 0),
    EXPIRATION_DATE         DATE DEFAULT SYSDATE,
CONSTRAINT PAYMENT_DETAIL_PK PRIMARY KEY (PAYMENT_DETAIL_ID));